(()=>{'use strict';
 const el=id=>document.getElementById('runner-'+id); if(!el('source'))return;
 const nodeNames={ANNUAL:'年度',MONTHLY:'月度',TEN_DAY:'旬内','D-3':'D-3滚撮','D-2':'D-2滚撮','L3-A':'日前申报','STORAGE-DA':'日前储能','STORAGE-RT':'日内储能',CHAIN:'完整事前链路',L1:'L1合同',L2:'L2滚撮'};
 let catalog=[],busy=false,started=0,jobId=null;
 const buttons=[...document.querySelectorAll('[data-node]')];
 const json=(text,fallback)=>text.trim()?JSON.parse(text):fallback;
 const lock=value=>{busy=value;buttons.forEach(b=>b.disabled=value)};
 const fail=e=>{lock(false);el('progress-box').hidden=false;el('status').textContent='计算失败';el('message').textContent=e.message||String(e);el('message').className='runner-error'};
 const inputsBase=()=>({package:el('package').value,risk_lambda:Number(el('risk').value),annual_price:Number(el('annual').value),monthly_price:Number(el('monthly').value),ten_day_price:Number(el('tenday').value),storage:{assessment_basis:el('basis').value}});
 async function request(url,options){const r=await fetch(url,options);const j=await r.json();if(!r.ok)throw Error(j.error||r.statusText);return j;}
 async function refresh(){const j=await request('/api/catalog');catalog=j.results;const selected=el('upstream').value;el('upstream').replaceChildren(new Option('选择前一节点结果',''));for(const row of catalog)el('upstream').add(new Option(`${row.package} / λ=${row.risk_lambda} · ${nodeNames[row.node]||row.node} · ${row.status}`,row.id));el('upstream').value=selected;el('connection').textContent='本地计算服务已连接';}
 el('upstream').onchange=async()=>{const row=catalog.find(x=>x.id===el('upstream').value);if(!row)return;try{lock(true);const result=await request(row.result_url),p=result.inputs;el('package').value=p.package;el('risk').value=p.risk_lambda;el('annual').value=p.annual_price;el('monthly').value=p.monthly_price;el('tenday').value=p.ten_day_price;el('basis').value=p.storage?.assessment_basis||'grid_net_load';el('input').value='';el('source').value='upstream';lock(false);}catch(e){fail(e);}};
 el('example').onclick=()=>{el('input').value=JSON.stringify({fixed_until:4,actual_load_mwh:[2.1,2.0,1.9,2.0],actual_rt_price:[320,330,420,480],executed_storage:{charge_mwh:[0,0,0,0],discharge_mwh:[0,0,0,0],soc_mwh:[10,10,10,10]}},null,2);};
 async function poll(){try{const j=await request('/api/job/'+jobId);el('progress').value=j.progress;el('status').textContent=j.status==='DONE'?'计算完成':j.status==='ERROR'?'计算失败':j.status==='QUEUED'?'等待求解器':'正在计算';el('elapsed').textContent=((Date.now()-started)/1000).toFixed(1)+' 秒';el('message').textContent=j.message;el('log').textContent=(j.log||[]).map(x=>`${x.percent.toFixed(0)}% · ${x.message}`).join('\n');if(['RUNNING','QUEUED'].includes(j.status)){setTimeout(poll,600);return;}lock(false);if(j.status==='ERROR')throw Error(j.error);el('download').href=j.result_url;el('download').hidden=false;el('download').download='result.json';el('view').href=j.report_url;el('view').hidden=false;el('view').textContent='打开本次计算的曲线和成本结果 →';await refresh();el('upstream').value=j.result_id;el('source').value='upstream';}catch(e){fail(e);}}
 async function run(node){if(busy)return;try{const base=inputsBase(),extra=json(el('input').value,{});const inputs={...base,...extra,storage:{...base.storage,...extra.storage}};let upstream=null,upstream_id=null;if(el('source').value==='manual')upstream=json(el('manual').value,null);if(el('source').value==='upstream'){upstream_id=el('upstream').value;if(!upstream_id)throw Error('请选择一个已完成的上游结果。');}lock(true);started=Date.now();el('progress-box').hidden=false;el('message').className='';el('progress').value=0;el('download').hidden=true;el('view').hidden=true;el('status').textContent='提交 '+(nodeNames[node]||node);el('log').textContent='';const j=await request('/api/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({node,inputs,upstream,upstream_id})});jobId=j.job_id;poll();}catch(e){fail(e);}}
 buttons.forEach(b=>b.onclick=()=>run(b.dataset.node));
 if(location.protocol==='file:'){el('connection').textContent='离线报告 · 浏览结果可用';buttons.forEach(b=>b.disabled=true);el('message').textContent='要计算，请运行 python -m pifa_lingshou.web.server 并打开其HTTP地址。';el('progress-box').hidden=false;el('status').textContent='当前为离线模式';}else refresh().catch(()=>{el('connection').textContent='计算服务尚未连接';buttons.forEach(b=>b.disabled=true);});
})();
